# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='short_typename',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Краткое наименование для ссылок (лат.)'),
        ),
    ]
