# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasktype_short_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='short_typename',
            field=models.CharField(max_length=30, unique=True, verbose_name='Краткое наименование для ссылок (лат.)'),
        ),
    ]
