# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20160518_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notify_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уведомить за (дней)'),
        ),
    ]
