# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task.TaskType', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
