# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('ACCEPTED', 'В работе'), ('CLOSED', 'Закрыта')], default='NEW', max_length=30, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
