# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AddField(
            model_name='usertaskprefs',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='usertaskprefs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
