# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_auto_20160529_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='usertaskprefs',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertaskprefs',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('ACCEPTED', 'В работе'), ('CLOSED', 'Закрыта')], default=1, max_length=30, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserTaskPrefs',
        ),
        migrations.AddField(
            model_name='taskuserpriority',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskuserpriority',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
