# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20160605_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Задача')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Крайний срок')),
                ('notify_before', models.IntegerField(blank=True, null=True, verbose_name='Уведомить за (дней)')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Когда создана')),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Когда изменена')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('ACCEPTED', 'В работе'), ('CLOSED', 'Закрыта')], max_length=30, verbose_name='Статус')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='Когда закрыта')),
                ('close_reason', models.CharField(blank=True, choices=[('CT', 'Завершено'), ('DU', 'Дублирует существующую'), ('WF', 'Отменено')], max_length=2, null=True, verbose_name='Тип закрытия')),
                ('prty', models.IntegerField(default=0, verbose_name='Приоритет (не задавать вручную!)')),
            ],
            options={
                'ordering': ['-prty'],
                'db_table': 'task_vtask',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='taskuserpriority',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение приоритета'),
        ),
    ]
