# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20160606_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Частная'),
        ),
        migrations.AddField(
            model_name='taskuserpriority',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение приоритета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('CT', 'Решено'), ('DU', 'Дублирует существующую'), ('WF', 'Отменено')], max_length=2, null=True, verbose_name='Тип закрытия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
    ]

