# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20160622_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код параметра')),
                ('name', models.CharField(max_length=100, verbose_name='Человекочитаемое название параметра')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='Родительская задача'),
        ),
    ]

