# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20160611_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
    ]
