# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20160611_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Частная'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('CT', 'Решено'), ('DU', 'Дублирует существующую'), ('WF', 'Отменено')], max_length=2, null=True, verbose_name='Тип закрытия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='Родительская задача'),
        ),
    ]
